spring:
  application:
    name: order
  jpa:
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_sell?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8082
test: test1
