spring:
  application:
    name: product
  jpa:
    show-sql: true
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud_sell?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&useSSL=false
server:
  port: 8081
